import os
import re

workspace_dir = os.path.dirname(os.path.abspath(__file__))
output_file = os.path.join(workspace_dir, "A1_System_Test_Plan_Compiled.md")

# Order of files as defined by the Table of Contents
ordered_files = [
    "01_Introduction/A1_Scope_and_Purpose.md",
    "01_Introduction/GLOBAL_Abbreviations.md",
    "01_Introduction/GLOBAL_White_Box_Testing_Strategy.md",
    "01_Introduction/GLOBAL_Black_Box_Testing_Strategy.md",
    "01_Introduction/GLOBAL_Functional_Testing_Definition.md",
    "01_Introduction/GLOBAL_Non_Functional_Testing_Definition.md",
    "02_System_Overview/A1_System_Overview_Handunit.md",
    "02_System_Overview/A1_System_Overview_Tube.md",
    "02_System_Overview/A1_System_Overview_Nozzle.md",
    "02_System_Overview/A1_System_Overview_Charger.md",
    "02_System_Overview/A1_System_Overview_Cloud.md",
    "03_Product_Requirements/A1_Requirements_and_Claims.md",
    "03_Product_Requirements/A1_User_Stories.md",
    "03_Product_Requirements/A1_Technical_Models.md",
    "04_Test_Strategy/A1_Technical_Models.md",
    "04_Test_Strategy/A1_Functional_Testing.md",
    "04_Test_Strategy/A1_Non_Functional_Testing.md",
    "04_Test_Strategy/GLOBAL_Static_Testing.md",
    "04_Test_Strategy/A1_Goal_with_the_Test.md",
    "04_Test_Strategy/GLOBAL_Item_Pass_Fail_Criteria.md",
    "04_Test_Strategy/GLOBAL_Entry_Criteria.md",
    "04_Test_Strategy/GLOBAL_Exit_Criteria.md",
    "04_Test_Strategy/GLOBAL_Quality_Assurance.md",
    "04_Test_Strategy/A1_Test_Deliverables.md",
    "04_Test_Strategy/GLOBAL_Test_Tasks.md",
    "05_Organization_Tools_Environment/A1_Project_Roles.md",
    "05_Organization_Tools_Environment/GLOBAL_Test_Management_Tools.md",
    "05_Organization_Tools_Environment/GLOBAL_Test_Environment_Shanghai_Lab.md",
    "05_Organization_Tools_Environment/GLOBAL_Test_Environment_Kwonnie_Lab.md",
    "05_Organization_Tools_Environment/A1_Project_Timeline_Overview.md",
    "05_Organization_Tools_Environment/A1_CTV_Time_Plan.md",
    "06_Test_Specification/A1_Test_Specification.md",
    "06_Test_Specification/A1_Appendix_A_Test_Specification_List.md",
]

compiled_content = []
compiled_content.append("# System Test Plan - Project A1 (Consolidated)\n")
compiled_content.append("> [!NOTE]")
compiled_content.append("> This is an automatically compiled consolidated test plan document. Do not edit this file directly. Instead, make changes to the individual modular files under the chapter directories and run `python compile_test_plan.py` to recompile.\n")
compiled_content.append("---")

footer_pattern = re.compile(r"\n+---\s*\n+\[« Back to Table of Contents\]\(\.\./README\.md\)\s*\n*")
link_pattern = re.compile(r"(\!?)\[([^\]]*)\]\(([^)]+)\)")

for file_rel in ordered_files:
    file_path = os.path.join(workspace_dir, file_rel)
    if not os.path.exists(file_path):
        print(f"[ERROR] Missing file in sequence: {file_rel}")
        continue
    
    file_dir = os.path.dirname(file_rel)
    
    with open(file_path, "r", encoding="utf-8") as f:
        file_content = f.read()
    
    # 1. Clean the navigation footers
    cleaned_content = footer_pattern.sub("", file_content)
    
    # 2. Adjust relative links and image paths to be relative to root
    def adjust_link(match):
        prefix = match.group(1)
        text = match.group(2)
        link = match.group(3)
        
        # Skip absolute, external, and network share paths
        if link.startswith(("http://", "https://", "U:", "/")):
            return match.group(0)
            
        # Resolve path relative to file_dir
        resolved = os.path.normpath(os.path.join(file_dir, link)).replace("\\", "/")
        return f"{prefix}[{text}](./{resolved})"
        
    cleaned_content = link_pattern.sub(adjust_link, cleaned_content)
    
    compiled_content.append(cleaned_content.strip())
    compiled_content.append("\n---\n")

# Write to consolidated output file
with open(output_file, "w", encoding="utf-8") as out:
    out.write("\n".join(compiled_content))

print(f"[SUCCESS] Test Plan consolidated successfully into: {output_file}")
